mutation checkoutCreate($input: CheckoutCreateInput!) {
  checkoutCreate(input: $input) {
    checkout {
      id
      email
      lineItems(first: 100) {
        nodes {
          id
          title
          quantity
          unitPrice {
            currencyCode
            amount
          }
        }
      }
    }
    checkoutUserErrors {
      message
    }
    queueToken
  }
}
