


query getCollections($first: Int!, $query:String){

  collections(first:$first,query:$query){

      nodes{
        id
        title
        description
        descriptionHtml
        handle
        image{
          id
          src
        }
        products(first:5){

            nodes{
              id
              title
              handle
            }

        }
      }
    
  }
}

query getCollectionByHandle($handle:String!, $first:Int){
  collection(handle:$handle){
    id
  title
  description
  descriptionHtml
  handle
  image{
    id
    src
  }
  products(first:$first){

      nodes{
        id
        images(first:1){

            nodes{
              src
              thumbnail: url(transform:{maxWidth:960})

            }
          
        }
        totalInventory
        title
        description
        handle
        priceRange{
          maxVariantPrice{
            amount
            currencyCode
          }
        }
        variants(first: 5) {

            nodes {
              id
              title
              priceV2 {
                amount
                currencyCode
              }
            }

        }
        tags
      }
    
  }

  }
}

