


query getCollections($first: Int!, $query:String){

  collections(first:$first,query:$query){
    edges{
      node{
        id
        title
        description
        descriptionHtml
        handle
        image{
          id
          src
        }
  products(first:5){
    edges{
      node{
        id
        title
      }
    }
  }
      }
    }
  }
}

query getCollectionByHandle($handle:String!){
  collection(handle:$handle){
    id
  title
  description
  descriptionHtml
  handle
  image{
    id
    src
  }
  products(first:5){
    edges{
      node{
        id
        images(first:1){
          edges{ 
            node{
              src
            }
          }
        }
        title
        description
        handle
        priceRange{
          maxVariantPrice{
            amount
            currencyCode
          }
        }
        variants(first: 4) {
          edges {
            node {
              id
              title
              priceV2 {
                amount
                currencyCode
              }
            }
          }
        }
        tags
      }
    }
  }

  }
}

