
query Products($first: Int!, $query: String, $after:String) {
  products(first: $first, query: $query, after:$after) {
    pageInfo{
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    nodes {
      id     
      images(first: 5) {
        nodes {
          src
          thumbnail: url(transform:{maxWidth:360})
        }
      }
      
      title
      description
      handle
      priceRange {
        maxVariantPrice {
          amount
          currencyCode
        }
      }
      variants(first: 4) {
        nodes {
          id
          title
          priceV2 {
            amount
            currencyCode
          }
        }
      }
      tags
    }
  }
}

query getProductByHandle($handle: String) {
  product(handle: $handle) {
    id
    seo {
        title
        description
      }
    images(first: 10) {
      nodes {
        src
        thumbnail: url(transform:{maxWidth:360})

      }
    }
    title
    description
    descriptionHtml
    handle
    priceRange {
      maxVariantPrice {
        amount
        currencyCode
      }
    }
    metafields(identifiers:[{namespace: "descriptors", key: "care_guide"},{namespace: "descriptors", key: "customization"},{namespace: "custom", key: "packaging"}]) {
  
        value
        key
        description
      }
    collections(first: 5) {
      nodes {
        title
        handle
      }
    }
    variants(first: 5) {
      nodes {
        id
        title
        priceV2 {
          amount
          currencyCode
        }
      }
    }
    tags
  }
}

query getProductRecommendations($id: ID!) {
  productRecommendations(productId: $id) {
    id
    images(first: 1) {
      nodes {
        src
        thumbnail: url(transform:{maxWidth:240})

      }
    }
    title
    description
    handle
    priceRange {
      maxVariantPrice {
        amount
        currencyCode
      }
    }
  }
}
