query Products ($first: Int!, $query:String){
  products(first:$first,query:$query){
    edges{
      node{
        id
        images(first:1){
          edges{ 
            node{
              src
            }
          }
        }
        title
        description
        handle
        priceRange{
          maxVariantPrice{
            amount
            currencyCode
          }
        }
        variants(first: 4) {
          edges {
            node {
              id
              title
              priceV2 {
                amount
                currencyCode
              }
            }
          }
        }
        tags
      }
    }
  }
}

query getProductByHandle($handle: String) {
  product(handle:$handle) {
    id
    images(first:1){
      edges{ 
        node{
          src
        }
      }
    }
    title
    description
    handle
    priceRange{
      maxVariantPrice{
        amount
        currencyCode
      }
    }
    variants(first: 4) {
      edges {
        node {
          id
          title
          priceV2 {
            amount
            currencyCode
          }
        }
      }
    }
    tags
  }
}